name: Manually GeneratePR

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: ブランチ
        options: 
        - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c auto/${{ github.event.inputs.target }}_${{ env.CURRENT_DATETIME }}
          git push -u origin auto/${{ github.event.inputs.target }}_${{ env.CURRENT_DATETIME }}

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Generate file
        run: touch hoge

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: auto/${{ github.event.inputs.target }}_${{ env.CURRENT_DATETIME }}
          message: "auto: 型ファイル自動作成"
          default_author: github_actions

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: auto/${{ github.event.inputs.target }}_${{ env.CURRENT_DATETIME }}
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: "[AUTO]型定義ファイル作成"
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
