name: Auto GeneratePR

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c auto/update_${{ env.CURRENT_DATETIME }}
          git push -u origin auto/update_${{ env.CURRENT_DATETIME }}

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Generate file
        run: touch hoge

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: auto/update_${{ env.CURRENT_DATETIME }}
          message: "auto: 型ファイル自動作成"
          default_author: github_actions

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: auto/update_${{ env.CURRENT_DATETIME }}
          destination_branch: ${{ github.base_ref }}
          pr_title: "[AUTO]型定義ファイル作成"
          github_token: ${{ secrets.GITHUB_TOKEN }}
